---
# tasks file for roles/load-balancer

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install HAProxy software
  package:
    name: "haproxy"
    state: present

- name: Copy configuration file
  template:
    src: "haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: restart lbserver

- name: Starting load balancer service
  service:
    name: "haproxy"
    state: started
